/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BarberRouteImport } from './routes/barber'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BarberIndexRouteImport } from './routes/barber.index'
import { Route as BarberStatsRouteImport } from './routes/barber.stats'
import { Route as BarberSettingsRouteImport } from './routes/barber.settings'
import { Route as BarberReviewsRouteImport } from './routes/barber.reviews'
import { Route as BarberProfileRouteImport } from './routes/barber.profile'
import { Route as BarberNotificationsRouteImport } from './routes/barber.notifications'
import { Route as BarberMarketingRouteImport } from './routes/barber.marketing'
import { Route as BarberHelpRouteImport } from './routes/barber.help'
import { Route as BarberEarningsRouteImport } from './routes/barber.earnings'
import { Route as BarberClientsRouteImport } from './routes/barber.clients'
import { Route as BarberChatRouteImport } from './routes/barber.chat'
import { Route as BarberCalendarRouteImport } from './routes/barber.calendar'
import { Route as BarberBookingsRouteImport } from './routes/barber.bookings'
import { Route as BarberSalonViewIndexRouteImport } from './routes/barber.salon-view.index'
import { Route as BarberSalonViewReviewsRouteImport } from './routes/barber.salon-view.reviews'
import { Route as BarberSalonViewGalleryRouteImport } from './routes/barber.salon-view.gallery'

const BarberRoute = BarberRouteImport.update({
  id: '/barber',
  path: '/barber',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BarberIndexRoute = BarberIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BarberRoute,
} as any)
const BarberStatsRoute = BarberStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => BarberRoute,
} as any)
const BarberSettingsRoute = BarberSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => BarberRoute,
} as any)
const BarberReviewsRoute = BarberReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => BarberRoute,
} as any)
const BarberProfileRoute = BarberProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => BarberRoute,
} as any)
const BarberNotificationsRoute = BarberNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => BarberRoute,
} as any)
const BarberMarketingRoute = BarberMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => BarberRoute,
} as any)
const BarberHelpRoute = BarberHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => BarberRoute,
} as any)
const BarberEarningsRoute = BarberEarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => BarberRoute,
} as any)
const BarberClientsRoute = BarberClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => BarberRoute,
} as any)
const BarberChatRoute = BarberChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => BarberRoute,
} as any)
const BarberCalendarRoute = BarberCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => BarberRoute,
} as any)
const BarberBookingsRoute = BarberBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => BarberRoute,
} as any)
const BarberSalonViewIndexRoute = BarberSalonViewIndexRouteImport.update({
  id: '/salon-view/',
  path: '/salon-view/',
  getParentRoute: () => BarberRoute,
} as any)
const BarberSalonViewReviewsRoute = BarberSalonViewReviewsRouteImport.update({
  id: '/salon-view/reviews',
  path: '/salon-view/reviews',
  getParentRoute: () => BarberRoute,
} as any)
const BarberSalonViewGalleryRoute = BarberSalonViewGalleryRouteImport.update({
  id: '/salon-view/gallery',
  path: '/salon-view/gallery',
  getParentRoute: () => BarberRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/barber': typeof BarberRouteWithChildren
  '/barber/bookings': typeof BarberBookingsRoute
  '/barber/calendar': typeof BarberCalendarRoute
  '/barber/chat': typeof BarberChatRoute
  '/barber/clients': typeof BarberClientsRoute
  '/barber/earnings': typeof BarberEarningsRoute
  '/barber/help': typeof BarberHelpRoute
  '/barber/marketing': typeof BarberMarketingRoute
  '/barber/notifications': typeof BarberNotificationsRoute
  '/barber/profile': typeof BarberProfileRoute
  '/barber/reviews': typeof BarberReviewsRoute
  '/barber/settings': typeof BarberSettingsRoute
  '/barber/stats': typeof BarberStatsRoute
  '/barber/': typeof BarberIndexRoute
  '/barber/salon-view/gallery': typeof BarberSalonViewGalleryRoute
  '/barber/salon-view/reviews': typeof BarberSalonViewReviewsRoute
  '/barber/salon-view/': typeof BarberSalonViewIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/barber/bookings': typeof BarberBookingsRoute
  '/barber/calendar': typeof BarberCalendarRoute
  '/barber/chat': typeof BarberChatRoute
  '/barber/clients': typeof BarberClientsRoute
  '/barber/earnings': typeof BarberEarningsRoute
  '/barber/help': typeof BarberHelpRoute
  '/barber/marketing': typeof BarberMarketingRoute
  '/barber/notifications': typeof BarberNotificationsRoute
  '/barber/profile': typeof BarberProfileRoute
  '/barber/reviews': typeof BarberReviewsRoute
  '/barber/settings': typeof BarberSettingsRoute
  '/barber/stats': typeof BarberStatsRoute
  '/barber': typeof BarberIndexRoute
  '/barber/salon-view/gallery': typeof BarberSalonViewGalleryRoute
  '/barber/salon-view/reviews': typeof BarberSalonViewReviewsRoute
  '/barber/salon-view': typeof BarberSalonViewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/barber': typeof BarberRouteWithChildren
  '/barber/bookings': typeof BarberBookingsRoute
  '/barber/calendar': typeof BarberCalendarRoute
  '/barber/chat': typeof BarberChatRoute
  '/barber/clients': typeof BarberClientsRoute
  '/barber/earnings': typeof BarberEarningsRoute
  '/barber/help': typeof BarberHelpRoute
  '/barber/marketing': typeof BarberMarketingRoute
  '/barber/notifications': typeof BarberNotificationsRoute
  '/barber/profile': typeof BarberProfileRoute
  '/barber/reviews': typeof BarberReviewsRoute
  '/barber/settings': typeof BarberSettingsRoute
  '/barber/stats': typeof BarberStatsRoute
  '/barber/': typeof BarberIndexRoute
  '/barber/salon-view/gallery': typeof BarberSalonViewGalleryRoute
  '/barber/salon-view/reviews': typeof BarberSalonViewReviewsRoute
  '/barber/salon-view/': typeof BarberSalonViewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/barber'
    | '/barber/bookings'
    | '/barber/calendar'
    | '/barber/chat'
    | '/barber/clients'
    | '/barber/earnings'
    | '/barber/help'
    | '/barber/marketing'
    | '/barber/notifications'
    | '/barber/profile'
    | '/barber/reviews'
    | '/barber/settings'
    | '/barber/stats'
    | '/barber/'
    | '/barber/salon-view/gallery'
    | '/barber/salon-view/reviews'
    | '/barber/salon-view/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/barber/bookings'
    | '/barber/calendar'
    | '/barber/chat'
    | '/barber/clients'
    | '/barber/earnings'
    | '/barber/help'
    | '/barber/marketing'
    | '/barber/notifications'
    | '/barber/profile'
    | '/barber/reviews'
    | '/barber/settings'
    | '/barber/stats'
    | '/barber'
    | '/barber/salon-view/gallery'
    | '/barber/salon-view/reviews'
    | '/barber/salon-view'
  id:
    | '__root__'
    | '/'
    | '/barber'
    | '/barber/bookings'
    | '/barber/calendar'
    | '/barber/chat'
    | '/barber/clients'
    | '/barber/earnings'
    | '/barber/help'
    | '/barber/marketing'
    | '/barber/notifications'
    | '/barber/profile'
    | '/barber/reviews'
    | '/barber/settings'
    | '/barber/stats'
    | '/barber/'
    | '/barber/salon-view/gallery'
    | '/barber/salon-view/reviews'
    | '/barber/salon-view/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BarberRoute: typeof BarberRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/barber': {
      id: '/barber'
      path: '/barber'
      fullPath: '/barber'
      preLoaderRoute: typeof BarberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/barber/': {
      id: '/barber/'
      path: '/'
      fullPath: '/barber/'
      preLoaderRoute: typeof BarberIndexRouteImport
      parentRoute: typeof BarberRoute
    }
    '/barber/stats': {
      id: '/barber/stats'
      path: '/stats'
      fullPath: '/barber/stats'
      preLoaderRoute: typeof BarberStatsRouteImport
      parentRoute: typeof BarberRoute
    }
    '/barber/settings': {
      id: '/barber/settings'
      path: '/settings'
      fullPath: '/barber/settings'
      preLoaderRoute: typeof BarberSettingsRouteImport
      parentRoute: typeof BarberRoute
    }
    '/barber/reviews': {
      id: '/barber/reviews'
      path: '/reviews'
      fullPath: '/barber/reviews'
      preLoaderRoute: typeof BarberReviewsRouteImport
      parentRoute: typeof BarberRoute
    }
    '/barber/profile': {
      id: '/barber/profile'
      path: '/profile'
      fullPath: '/barber/profile'
      preLoaderRoute: typeof BarberProfileRouteImport
      parentRoute: typeof BarberRoute
    }
    '/barber/notifications': {
      id: '/barber/notifications'
      path: '/notifications'
      fullPath: '/barber/notifications'
      preLoaderRoute: typeof BarberNotificationsRouteImport
      parentRoute: typeof BarberRoute
    }
    '/barber/marketing': {
      id: '/barber/marketing'
      path: '/marketing'
      fullPath: '/barber/marketing'
      preLoaderRoute: typeof BarberMarketingRouteImport
      parentRoute: typeof BarberRoute
    }
    '/barber/help': {
      id: '/barber/help'
      path: '/help'
      fullPath: '/barber/help'
      preLoaderRoute: typeof BarberHelpRouteImport
      parentRoute: typeof BarberRoute
    }
    '/barber/earnings': {
      id: '/barber/earnings'
      path: '/earnings'
      fullPath: '/barber/earnings'
      preLoaderRoute: typeof BarberEarningsRouteImport
      parentRoute: typeof BarberRoute
    }
    '/barber/clients': {
      id: '/barber/clients'
      path: '/clients'
      fullPath: '/barber/clients'
      preLoaderRoute: typeof BarberClientsRouteImport
      parentRoute: typeof BarberRoute
    }
    '/barber/chat': {
      id: '/barber/chat'
      path: '/chat'
      fullPath: '/barber/chat'
      preLoaderRoute: typeof BarberChatRouteImport
      parentRoute: typeof BarberRoute
    }
    '/barber/calendar': {
      id: '/barber/calendar'
      path: '/calendar'
      fullPath: '/barber/calendar'
      preLoaderRoute: typeof BarberCalendarRouteImport
      parentRoute: typeof BarberRoute
    }
    '/barber/bookings': {
      id: '/barber/bookings'
      path: '/bookings'
      fullPath: '/barber/bookings'
      preLoaderRoute: typeof BarberBookingsRouteImport
      parentRoute: typeof BarberRoute
    }
    '/barber/salon-view/': {
      id: '/barber/salon-view/'
      path: '/salon-view'
      fullPath: '/barber/salon-view/'
      preLoaderRoute: typeof BarberSalonViewIndexRouteImport
      parentRoute: typeof BarberRoute
    }
    '/barber/salon-view/reviews': {
      id: '/barber/salon-view/reviews'
      path: '/salon-view/reviews'
      fullPath: '/barber/salon-view/reviews'
      preLoaderRoute: typeof BarberSalonViewReviewsRouteImport
      parentRoute: typeof BarberRoute
    }
    '/barber/salon-view/gallery': {
      id: '/barber/salon-view/gallery'
      path: '/salon-view/gallery'
      fullPath: '/barber/salon-view/gallery'
      preLoaderRoute: typeof BarberSalonViewGalleryRouteImport
      parentRoute: typeof BarberRoute
    }
  }
}

interface BarberRouteChildren {
  BarberBookingsRoute: typeof BarberBookingsRoute
  BarberCalendarRoute: typeof BarberCalendarRoute
  BarberChatRoute: typeof BarberChatRoute
  BarberClientsRoute: typeof BarberClientsRoute
  BarberEarningsRoute: typeof BarberEarningsRoute
  BarberHelpRoute: typeof BarberHelpRoute
  BarberMarketingRoute: typeof BarberMarketingRoute
  BarberNotificationsRoute: typeof BarberNotificationsRoute
  BarberProfileRoute: typeof BarberProfileRoute
  BarberReviewsRoute: typeof BarberReviewsRoute
  BarberSettingsRoute: typeof BarberSettingsRoute
  BarberStatsRoute: typeof BarberStatsRoute
  BarberIndexRoute: typeof BarberIndexRoute
  BarberSalonViewGalleryRoute: typeof BarberSalonViewGalleryRoute
  BarberSalonViewReviewsRoute: typeof BarberSalonViewReviewsRoute
  BarberSalonViewIndexRoute: typeof BarberSalonViewIndexRoute
}

const BarberRouteChildren: BarberRouteChildren = {
  BarberBookingsRoute: BarberBookingsRoute,
  BarberCalendarRoute: BarberCalendarRoute,
  BarberChatRoute: BarberChatRoute,
  BarberClientsRoute: BarberClientsRoute,
  BarberEarningsRoute: BarberEarningsRoute,
  BarberHelpRoute: BarberHelpRoute,
  BarberMarketingRoute: BarberMarketingRoute,
  BarberNotificationsRoute: BarberNotificationsRoute,
  BarberProfileRoute: BarberProfileRoute,
  BarberReviewsRoute: BarberReviewsRoute,
  BarberSettingsRoute: BarberSettingsRoute,
  BarberStatsRoute: BarberStatsRoute,
  BarberIndexRoute: BarberIndexRoute,
  BarberSalonViewGalleryRoute: BarberSalonViewGalleryRoute,
  BarberSalonViewReviewsRoute: BarberSalonViewReviewsRoute,
  BarberSalonViewIndexRoute: BarberSalonViewIndexRoute,
}

const BarberRouteWithChildren =
  BarberRoute._addFileChildren(BarberRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BarberRoute: BarberRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
